# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lockdowndates/',
                'doc_host': 'https://seanyboi.github.io',
                'git_url': 'https://github.com/seanyboi/lockdowndates/tree/main/',
                'lib_path': 'lockdowndates'},
  'syms': { 'lockdowndates.core': { 'lockdowndates.core.LockdownDates': ('core.html#lockdowndates', 'lockdowndates/core.py'),
                                    'lockdowndates.core.LockdownDates.__init__': ( 'core.html#lockdowndates.__init__',
                                                                                   'lockdowndates/core.py'),
                                    'lockdowndates.core.LockdownDates.dates': ('core.html#lockdowndates.dates', 'lockdowndates/core.py'),
                                    'lockdowndates.core.LockdownDates.engineer_df': ( 'core.html#lockdowndates.engineer_df',
                                                                                      'lockdowndates/core.py'),
                                    'lockdowndates.core.LockdownDates.fetch': ('core.html#lockdowndates.fetch', 'lockdowndates/core.py'),
                                    'lockdowndates.core.LockdownDates.filter_df': ( 'core.html#lockdowndates.filter_df',
                                                                                    'lockdowndates/core.py')},
            'lockdowndates.index': {}}}