# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"LockdownDates": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://seanyboi.github.io/lockdowndates/"

git_url = "https://github.com/seanyboi/lockdowndates/tree/main/"

def custom_doc_links(name): return None
