package:
  name: lockdowndates
  version: 0.0.1
source:
  sha256: 8b518b4032a02b3fae316c21115414c754559b665d58ae3fbe125834c2987dba
  url: https://files.pythonhosted.org/packages/0d/7f/bd2fc4297564d41f39a6e4a65f4b0341422bae3ec799b38d0909adf81bed/lockdowndates-0.0.1.tar.gz
about:
  dev_url: https://seanyboi.github.io
  doc_url: https://seanyboi.github.io
  home: https://seanyboi.github.io
  license: Apache Software
  license_family: APACHE
  summary: Retrieve the dates of the restrictions in countries imposed by governments
    around the world during the covid-19 pandemic.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - seanyboi
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas==1.1.4
  - pyarrow
  run:
  - pip
  - python
  - packaging
  - pandas==1.1.4
  - pyarrow
test:
  imports:
  - lockdowndates
