package:
  name: lockdowndates
  version: 0.0.3
source:
  sha256: cc7a5a8c9e8748f79b30810916f594660653372951359af7ad88155b1f53dbbe
  url: https://files.pythonhosted.org/packages/14/a4/de3fa0f0821a89b26a6d35439e4d33e75de9f4b1313ea64fe85fbf43a9d2/lockdowndates-0.0.3.tar.gz
about:
  dev_url: https://seanyboi.github.io
  doc_url: https://seanyboi.github.io
  home: https://seanyboi.github.io
  license: Apache Software
  license_family: APACHE
  summary: Retrieve the dates of the restrictions in countries imposed by governments
    around the world during the covid-19 pandemic.
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - seanyboi
requirements:
  host:
  - pip
  - python
  - packaging
  - pandas==1.4.0
  - pyarrow
  run:
  - pip
  - python
  - packaging
  - pandas==1.4.0
  - pyarrow
test:
  imports:
  - lockdowndates
