# This is a basic workflow to help you get started with Actions

name: Fetch lockdown dates.

# Controls when the workflow will run
on:
  schedule:
    # Runs "at hour 6 past every day" (see https://crontab.guru)
    - cron: '00 6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: keithweaver/aws-s3-github-action@v1.0.0 # Verifies the recursive flag
        name: Copy Folder
        with:
          command: cp
          source: ./data/
          destination: s3://lockdowndates/data
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: eu-west-1
          flags: --recursive
